### PR TITLE
Responsive Website! The Next Web clone.

### PR DESCRIPTION
**Pull request by lmaldonadoch**
In this project, we applied the knowledge acquired from the material on the Responsive Website curse along with all the other knowledge we had acquired over the past projects. On this project we were able to:
- Build a complete website from scratch with no Frameworks.
- Make a website fully responsive.
- Practice our previously acquired knowledge on HTML and CSS including Grid, Flexbox, Float, Background Images, and Background Gradients.

The requirements we were able to meet for this project were:

## General requirements:
- [x] Add a descriptive README file to your repositories as described here.
- [x] Use meaningful names for your Pull Requests and add a short summary of its content as described here.
- [x] Use descriptive commit messages as described here.
- [x] Do not commit files that are not related to the project. Instead, add them to .gitignore file.
- [x] Do not commit inline comments. They will make your project look messy. If you need to review a previous version of your code, you can always use git history.

## Section:
- [x] Keep your code clean.
- [x] Remember to use semantic HTML.
- [x] Validate your HTML markup with validator (as described here).
- [x] Make sure you DON’T make common mistakes in your CSS styles.

## Project-specific
- [x] Align all elements with float and flex or grid.
- [x] Use a mobile-first approach when dealing with media-queries with 2 breakpoints (you should figure out the exact width for each breakpoint by yourself).
- [x] Remember to double-check if your page layout does not break on smaller screens.

### CODE REVIEW

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @lmaldonadoch & @Jmagero  :wave:
-
You have done a splendid job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
- [ ] There is an issue with small screens rendering. The images, during scroll, seem to be going over the header. Kindly fix that.
small_screen_clone

- [ ] In small the screen, all your contents are covering the entire with  of the screen saved for the contents in the apps section, they have to match this; 👇 
small_screen
- [ ] Add a live link to your README file. Good job with the explanations. While at it also do checkout for grammatical errors. 
- [ ]  [OPTIONAL] - Jocyline, mind making your handles visible in these links? Thanks.
readme

Please make these changes and submit another review request.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by lmaldonadoch** [comment]
Hi! Thanks for the comments! Here are the corrections:
- [x] There is an issue with small screens rendering. The images, during scroll, seem to be going over the header. Kindly fix that.

> We added a z-index to fix it.

- [x] In small the screen, all your contents are covering the entire with  of the screen saved for the contents in the apps section, they have to match this; 👇 

> We fixed it adding some width rules to the section.

- [x] Add a live link to your README file. Good job with the explanations. While at it also do checkout for grammatical errors. 

> Done! We are very sorry about that, we completely forgot.

- [x]  [OPTIONAL] - Jocyline, mind making your handles visible in these links? Thanks.

> Done! Thanks for pointing it out!

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️  🚥 

Hi **TEAM**, you have done a great job working on the changes requested by the previous reviewer 👍 
Let us improve our project before moving on. Kindly find comments below:
- Let us fix the huge margins between the articles. Let us compare our version to that of the original
```Currently```
fm
```Original```
fm1
- ```The latest deals``` should align with the ```see all deals``` on small screen
- Kindly remember to make your names visible on the social handles of the README file as pointed out by the previous TSE

Kindly make these changes and submit another code review 👍 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack 😄

**Comment by lmaldonadoch** [comment]
Hi!

Thank you so much for the comment, it is solved!

- [x] - Let us fix the huge margins between the articles. Let us compare our version to that of the original

image

**Review by serdg0 — CHANGES_REQUESTED** [review]
**Status: Required Changes.**

Hi @Jmagero and @lmaldonadoch :v: :v: 

You have been doing a great job so far! We only need to fill 1 requirement to make this awesome project **outstanding**! :1st_place_medal: :1st_place_medal: 

- [ ] The allignment of 'Lates deals' and 'see all deals'. I attach the images below.

**Yours**
Selection_009

**Original**
Selection_010

Make this change and submit for another code review.

**Happy Coding!** :computer: :computer:

**Comment by lmaldonadoch** [comment]
Done...

**Review by serdg0 — APPROVED** [review]
### Status: Approved

Hello @lmaldonadoch and @Jmagero :v: :v: 

Congratulations to both on the great work in this project! :fireworks: :trophy: 

You are good to go and merge. Keep up the great work in the next project!

### Have fun coding! :computer: :computer:

**Pull request merged**
